version: '1'

services:

  # docker run \
  #    -p 9000:9000 \
  #    -p 9090:9090 \
  #    --name minio1 \
  #    -v D:\minio\data:/data \
  #    -e "MINIO_ROOT_USER=ROOTUSER" \
  #    -e "MINIO_ROOT_PASSWORD=CHANGEME123" \
  #    quay.io/minio/minio server /data --console-address ":9090"

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    volumes:
      - ./data/minio:/data
    ports:
      - '9000:9000'
      - '9090:9090'
    environment:
      - MINIO_ROOT_USER=username
      - MINIO_ROOT_PASSWORD=password
    command: server /data --console-address ":9090"
    networks:
      - minio


networks:
  minio:
    driver: bridge
    attachable: true
